# Generated by Django 3.1.4 on 2021-01-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
